[project]
name = "rss-downloader"
version = "0.1.0"
description = "A simple RSS link downloader written in Python."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "feedparser>=6.0.12",
    "requests>=2.32.5",
]
